"""Add job verification requirements fields

Revision ID: 1456ffde2e15
Revises: 42481afe038e
Create Date: 2025-12-14 20:02:19.860757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1456ffde2e15'
down_revision = '42481afe038e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('requires_verification_level', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('verified_candidates_only', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'verified_candidates_only')
    op.drop_column('jobs', 'requires_verification_level')
    # ### end Alembic commands ###
