"""Add dashboard_preferences to users

Revision ID: 1a5e4dae1c7a
Revises: fa883f5bdd02
Create Date: 2025-11-29 09:07:01.712539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5e4dae1c7a'
down_revision = 'fa883f5bdd02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dashboard_preferences', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dashboard_preferences')
    # ### end Alembic commands ###
