"""add_posts_comments_reactions_tables

Revision ID: 50303bdaea3f
Revises: sprint5_001
Create Date: 2026-05-02 07:13:11.226253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50303bdaea3f'
down_revision = 'sprint5_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('post_metadata', sa.Text(), nullable=True),
    sa.Column('media_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=512), nullable=True),
    sa.Column('external_url', sa.String(length=512), nullable=True),
    sa.Column('experience_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['work_experiences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_items_user_id'), 'portfolio_items', ['user_id'], unique=False)
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_reaction_post_user')
    )
    op.create_index(op.f('ix_reactions_id'), 'reactions', ['id'], unique=False)
    op.create_index(op.f('ix_reactions_post_id'), 'reactions', ['post_id'], unique=False)
    op.create_index(op.f('ix_reactions_user_id'), 'reactions', ['user_id'], unique=False)
    op.drop_table('resume_templates')
    op.create_index(op.f('ix_feed_signals_id'), 'feed_signals', ['id'], unique=False)
    op.drop_constraint(op.f('feed_signals_opportunity_id_fkey'), 'feed_signals', type_='foreignkey')
    op.drop_constraint(op.f('feed_signals_user_id_fkey'), 'feed_signals', type_='foreignkey')
    op.create_foreign_key(None, 'feed_signals', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'feed_signals', 'opportunities', ['opportunity_id'], ['id'])
    op.alter_column('opportunities', 'benefits',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON array of benefit strings',
               existing_nullable=True)
    op.alter_column('opportunities', 'required_documents',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON array of required document strings',
               existing_nullable=True)
    op.alter_column('opportunities', 'tags',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON array of tag strings',
               existing_nullable=True)
    op.alter_column('opportunities', 'red_flags',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON array of scam/fraud flag strings',
               existing_nullable=True)
    op.alter_column('opportunities', 'qualification_requirements',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON object {minimum: {...}, ideal: {...}}',
               existing_nullable=True)
    op.alter_column('opportunities', 'experience_requirements',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON object {minimum: {...}, ideal: {...}}',
               existing_nullable=True)
    op.alter_column('opportunities', 'skills_structured',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON array of {name, level} objects',
               existing_nullable=True)
    op.alter_column('opportunities', 'knowledge_requirements',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON object {minimum: [...], ideal: [...]}',
               existing_nullable=True)
    op.alter_column('opportunities', 'conditions_of_employment',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='JSON array of condition strings',
               existing_nullable=True)
    op.alter_column('opportunities', 'duration',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Contract/programme duration e.g. '12 months', 'Permanent'",
               existing_nullable=True)
    op.alter_column('opportunities', 'start_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Position/programme start date',
               existing_nullable=True)
    op.alter_column('opportunities', 'scam_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Fraud probability 0.0-1.0',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('opportunities', 'contact_website',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Company career page or main website URL',
               existing_nullable=True)
    op.drop_index(op.f('ix_jobs_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_source_url'), table_name='opportunities')
    op.create_index(op.f('ix_opportunities_ai_status'), 'opportunities', ['ai_status'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_source_platform'), 'opportunities', ['source_platform'], unique=False)
    op.create_unique_constraint(None, 'opportunities', ['source_url'])
    op.alter_column('opportunity_activity', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('opportunity_activity', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resume_versions', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index(op.f('ix_resume_versions_resume_id'), 'resume_versions', ['resume_id'], unique=False)
    op.drop_constraint(op.f('resume_versions_resume_id_fkey'), 'resume_versions', type_='foreignkey')
    op.drop_constraint(op.f('resume_versions_created_by_fkey'), 'resume_versions', type_='foreignkey')
    op.create_foreign_key(None, 'resume_versions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'resume_versions', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.drop_constraint(op.f('resumes_user_id_fkey'), 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_saved_jobs_id'), table_name='saved_opportunities')
    op.create_index(op.f('ix_saved_opportunities_id'), 'saved_opportunities', ['id'], unique=False)
    op.drop_constraint(op.f('user_feed_state_user_id_fkey'), 'user_feed_state', type_='foreignkey')
    op.create_foreign_key(None, 'user_feed_state', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'willing_to_relocate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'salary_negotiable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'salary_negotiable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'willing_to_relocate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'user_feed_state', type_='foreignkey')
    op.create_foreign_key(op.f('user_feed_state_user_id_fkey'), 'user_feed_state', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_saved_opportunities_id'), table_name='saved_opportunities')
    op.create_index(op.f('ix_saved_jobs_id'), 'saved_opportunities', ['id'], unique=False)
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key(op.f('resumes_user_id_fkey'), 'resumes', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_constraint(None, 'resume_versions', type_='foreignkey')
    op.drop_constraint(None, 'resume_versions', type_='foreignkey')
    op.create_foreign_key(op.f('resume_versions_created_by_fkey'), 'resume_versions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('resume_versions_resume_id_fkey'), 'resume_versions', 'resumes', ['resume_id'], ['id'])
    op.drop_index(op.f('ix_resume_versions_resume_id'), table_name='resume_versions')
    op.alter_column('resume_versions', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('opportunity_activity', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('opportunity_activity', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'opportunities', type_='unique')
    op.drop_index(op.f('ix_opportunities_source_platform'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_ai_status'), table_name='opportunities')
    op.create_index(op.f('ix_opportunities_source_url'), 'opportunities', ['source_url'], unique=True)
    op.create_index(op.f('ix_jobs_id'), 'opportunities', ['id'], unique=False)
    op.alter_column('opportunities', 'contact_website',
               existing_type=sa.VARCHAR(length=500),
               comment='Company career page or main website URL',
               existing_nullable=True)
    op.alter_column('opportunities', 'scam_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Fraud probability 0.0-1.0',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('opportunities', 'start_date',
               existing_type=sa.DATE(),
               comment='Position/programme start date',
               existing_nullable=True)
    op.alter_column('opportunities', 'duration',
               existing_type=sa.VARCHAR(length=100),
               comment="Contract/programme duration e.g. '12 months', 'Permanent'",
               existing_nullable=True)
    op.alter_column('opportunities', 'conditions_of_employment',
               existing_type=sa.TEXT(),
               comment='JSON array of condition strings',
               existing_nullable=True)
    op.alter_column('opportunities', 'knowledge_requirements',
               existing_type=sa.TEXT(),
               comment='JSON object {minimum: [...], ideal: [...]}',
               existing_nullable=True)
    op.alter_column('opportunities', 'skills_structured',
               existing_type=sa.TEXT(),
               comment='JSON array of {name, level} objects',
               existing_nullable=True)
    op.alter_column('opportunities', 'experience_requirements',
               existing_type=sa.TEXT(),
               comment='JSON object {minimum: {...}, ideal: {...}}',
               existing_nullable=True)
    op.alter_column('opportunities', 'qualification_requirements',
               existing_type=sa.TEXT(),
               comment='JSON object {minimum: {...}, ideal: {...}}',
               existing_nullable=True)
    op.alter_column('opportunities', 'red_flags',
               existing_type=sa.TEXT(),
               comment='JSON array of scam/fraud flag strings',
               existing_nullable=True)
    op.alter_column('opportunities', 'tags',
               existing_type=sa.TEXT(),
               comment='JSON array of tag strings',
               existing_nullable=True)
    op.alter_column('opportunities', 'required_documents',
               existing_type=sa.TEXT(),
               comment='JSON array of required document strings',
               existing_nullable=True)
    op.alter_column('opportunities', 'benefits',
               existing_type=sa.TEXT(),
               comment='JSON array of benefit strings',
               existing_nullable=True)
    op.drop_constraint(None, 'feed_signals', type_='foreignkey')
    op.drop_constraint(None, 'feed_signals', type_='foreignkey')
    op.create_foreign_key(op.f('feed_signals_user_id_fkey'), 'feed_signals', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('feed_signals_opportunity_id_fkey'), 'feed_signals', 'opportunities', ['opportunity_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_feed_signals_id'), table_name='feed_signals')
    op.create_table('resume_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('preview_image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('html_template_body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('resume_templates_pkey'))
    )
    op.drop_index(op.f('ix_reactions_user_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_post_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_portfolio_items_user_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
