"""add_verification_tokens

Revision ID: 5fb35329d2ab
Revises: sprint1_001_p1
Create Date: 2025-12-12 14:05:11.091971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb35329d2ab'
down_revision = 'sprint1_001_p1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_endorsements_id'), 'endorsements', ['id'], unique=False)
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    op.create_index(op.f('ix_profile_stars_id'), 'profile_stars', ['id'], unique=False)
    op.create_index(op.f('ix_profile_watches_id'), 'profile_watches', ['id'], unique=False)
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.add_column('verifications', sa.Column('token', sa.String(), nullable=True))
    op.add_column('verifications', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_verifications_id'), 'verifications', ['id'], unique=False)
    op.create_index(op.f('ix_verifications_token'), 'verifications', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_token'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_id'), table_name='verifications')
    op.drop_column('verifications', 'token_expires_at')
    op.drop_column('verifications', 'token')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_index(op.f('ix_profile_watches_id'), table_name='profile_watches')
    op.drop_index(op.f('ix_profile_stars_id'), table_name='profile_stars')
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.drop_index(op.f('ix_endorsements_id'), table_name='endorsements')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    # ### end Alembic commands ###
