"""add_user_persona_field

Revision ID: 6de5d41c5280
Revises: 20251113_resumes
Create Date: 2025-11-24 00:16:24.218602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6de5d41c5280'
down_revision = '20251113_resumes'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_templates')
    op.add_column('users', sa.Column('persona', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'persona')
    op.create_table('resume_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('preview_image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('html_template_body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('resume_templates_pkey'))
    )
    # ### end Alembic commands ###
