"""add_onboarding_fields

Revision ID: 6e8fdef75e26
Revises: 6de5d41c5280
Create Date: 2025-11-24 01:08:33.826214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8fdef75e26'
down_revision = '6de5d41c5280'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('primary_goal', sa.String(), nullable=True))
    op.add_column('users', sa.Column('industry', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'industry')
    op.drop_column('users', 'primary_goal')
    op.drop_column('users', 'experience_level')
    # ### end Alembic commands ###
