"""add_trust_score_and_verification_level

Revision ID: 78b3cc1671a9
Revises: 051a0da03408
Create Date: 2025-12-14 10:13:34.010292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b3cc1671a9'
down_revision = '051a0da03408'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trust_score', sa.Integer(), nullable=True))
    op.add_column('verifications', sa.Column('trust_level', sa.String(length=20), nullable=True))
    op.add_column('verifications', sa.Column('trust_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifications', 'trust_points')
    op.drop_column('verifications', 'trust_level')
    op.drop_column('users', 'trust_score')
    # ### end Alembic commands ###
