"""create_rating_requests_table

Revision ID: 82e9cbddf40e
Revises: d2a46ffae604
Create Date: 2025-12-13 08:41:33.087197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e9cbddf40e'
down_revision = 'd2a46ffae604'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('share_channel', sa.String(length=20), nullable=True),
    sa.Column('invitee_email', sa.String(length=255), nullable=True),
    sa.Column('invitee_phone', sa.String(length=50), nullable=True),
    sa.Column('invitee_name', sa.String(length=255), nullable=True),
    sa.Column('invitee_user_id', sa.Integer(), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role_at_company', sa.String(length=255), nullable=True),
    sa.Column('work_period_start', sa.DateTime(), nullable=True),
    sa.Column('work_period_end', sa.DateTime(), nullable=True),
    sa.Column('personal_message', sa.Text(), nullable=True),
    sa.Column('rater_verified_email', sa.String(length=255), nullable=True),
    sa.Column('rater_verified_phone', sa.String(length=50), nullable=True),
    sa.Column('rater_company_email', sa.String(length=255), nullable=True),
    sa.Column('rater_linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('contact_visible_to_requester', sa.Boolean(), nullable=True),
    sa.Column('contact_visible_to_public', sa.Boolean(), nullable=True),
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rating_id'], ['ratings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_requests_id'), 'rating_requests', ['id'], unique=False)
    op.create_index(op.f('ix_rating_requests_requester_id'), 'rating_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_rating_requests_token'), 'rating_requests', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_requests_token'), table_name='rating_requests')
    op.drop_index(op.f('ix_rating_requests_requester_id'), table_name='rating_requests')
    op.drop_index(op.f('ix_rating_requests_id'), table_name='rating_requests')
    op.drop_table('rating_requests')
    # ### end Alembic commands ###
