"""add_experience_and_portfolio_tables

Revision ID: 8b9064b250a1
Revises: f1a2b3c4d5e7
Create Date: 2025-12-18 05:00:29.023529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b9064b250a1'
down_revision = 'f1a2b3c4d5e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experiences_user_id'), 'work_experiences', ['user_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=512), nullable=True),
    sa.Column('external_url', sa.String(length=512), nullable=True),
    sa.Column('experience_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['work_experiences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_items_user_id'), 'portfolio_items', ['user_id'], unique=False)
    op.drop_index(op.f('ix_portal_jobs_category'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_company'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_external_id'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_is_active'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_location'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_opportunity_category'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_opportunity_type'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_posted_at'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_slug'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_source'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_title'), table_name='portal_jobs')
    op.drop_table('portal_jobs')
    op.add_column('opportunities', sa.Column('opportunity_type', sa.String(length=100), nullable=True))
    op.add_column('opportunities', sa.Column('category', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_jobs_id'), table_name='opportunities')
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.drop_column('opportunities', 'job_type')
    op.add_column('portal_opportunities', sa.Column('opportunity_type', sa.String(length=50), nullable=True))
    op.add_column('portal_opportunities', sa.Column('industry', sa.String(length=100), nullable=True))
    op.alter_column('portal_opportunities', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_portal_opportunities_category'), 'portal_opportunities', ['category'], unique=False)
    op.create_index(op.f('ix_portal_opportunities_company'), 'portal_opportunities', ['company'], unique=False)
    op.create_index(op.f('ix_portal_opportunities_external_id'), 'portal_opportunities', ['external_id'], unique=False)
    op.create_index(op.f('ix_portal_opportunities_id'), 'portal_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_portal_opportunities_industry'), 'portal_opportunities', ['industry'], unique=False)
    op.create_index(op.f('ix_portal_opportunities_is_active'), 'portal_opportunities', ['is_active'], unique=False)
    op.create_index(op.f('ix_portal_opportunities_location'), 'portal_opportunities', ['location'], unique=False)
    op.create_index(op.f('ix_portal_opportunities_posted_at'), 'portal_opportunities', ['posted_at'], unique=False)
    op.create_index(op.f('ix_portal_opportunities_slug'), 'portal_opportunities', ['slug'], unique=True)
    op.create_index(op.f('ix_portal_opportunities_source'), 'portal_opportunities', ['source'], unique=False)
    op.create_index(op.f('ix_portal_opportunities_title'), 'portal_opportunities', ['title'], unique=False)
    op.drop_column('portal_opportunities', 'job_type')
    op.add_column('saved_opportunities', sa.Column('opportunity_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_saved_jobs_id'), table_name='saved_opportunities')
    op.drop_index(op.f('ix_saved_jobs_job_id'), table_name='saved_opportunities')
    op.drop_index(op.f('ix_saved_jobs_user_id'), table_name='saved_opportunities')
    op.drop_constraint(op.f('unique_user_job'), 'saved_opportunities', type_='unique')
    op.create_index(op.f('ix_saved_opportunities_id'), 'saved_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_saved_opportunities_opportunity_id'), 'saved_opportunities', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_saved_opportunities_user_id'), 'saved_opportunities', ['user_id'], unique=False)
    op.create_unique_constraint('unique_user_opportunity', 'saved_opportunities', ['user_id', 'opportunity_id'])
    op.drop_constraint(op.f('saved_jobs_job_id_fkey'), 'saved_opportunities', type_='foreignkey')
    op.create_foreign_key(None, 'saved_opportunities', 'opportunities', ['opportunity_id'], ['id'])
    op.drop_column('saved_opportunities', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_opportunities', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'saved_opportunities', type_='foreignkey')
    op.create_foreign_key(op.f('saved_jobs_job_id_fkey'), 'saved_opportunities', 'opportunities', ['job_id'], ['id'])
    op.drop_constraint('unique_user_opportunity', 'saved_opportunities', type_='unique')
    op.drop_index(op.f('ix_saved_opportunities_user_id'), table_name='saved_opportunities')
    op.drop_index(op.f('ix_saved_opportunities_opportunity_id'), table_name='saved_opportunities')
    op.drop_index(op.f('ix_saved_opportunities_id'), table_name='saved_opportunities')
    op.create_unique_constraint(op.f('unique_user_job'), 'saved_opportunities', ['user_id', 'job_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_saved_jobs_user_id'), 'saved_opportunities', ['user_id'], unique=False)
    op.create_index(op.f('ix_saved_jobs_job_id'), 'saved_opportunities', ['job_id'], unique=False)
    op.create_index(op.f('ix_saved_jobs_id'), 'saved_opportunities', ['id'], unique=False)
    op.drop_column('saved_opportunities', 'opportunity_id')
    op.add_column('portal_opportunities', sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_portal_opportunities_title'), table_name='portal_opportunities')
    op.drop_index(op.f('ix_portal_opportunities_source'), table_name='portal_opportunities')
    op.drop_index(op.f('ix_portal_opportunities_slug'), table_name='portal_opportunities')
    op.drop_index(op.f('ix_portal_opportunities_posted_at'), table_name='portal_opportunities')
    op.drop_index(op.f('ix_portal_opportunities_location'), table_name='portal_opportunities')
    op.drop_index(op.f('ix_portal_opportunities_is_active'), table_name='portal_opportunities')
    op.drop_index(op.f('ix_portal_opportunities_industry'), table_name='portal_opportunities')
    op.drop_index(op.f('ix_portal_opportunities_id'), table_name='portal_opportunities')
    op.drop_index(op.f('ix_portal_opportunities_external_id'), table_name='portal_opportunities')
    op.drop_index(op.f('ix_portal_opportunities_company'), table_name='portal_opportunities')
    op.drop_index(op.f('ix_portal_opportunities_category'), table_name='portal_opportunities')
    op.alter_column('portal_opportunities', 'category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('portal_opportunities', 'industry')
    op.drop_column('portal_opportunities', 'opportunity_type')
    op.add_column('opportunities', sa.Column('job_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.create_index(op.f('ix_jobs_id'), 'opportunities', ['id'], unique=False)
    op.drop_column('opportunities', 'category')
    op.drop_column('opportunities', 'opportunity_type')
    op.create_table('portal_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('location_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('salary_min', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_max', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('salary_period', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description_html', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('experience_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('education_requirement', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('years_experience_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('years_experience_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('opportunity_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('opportunity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('views_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('applies_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('saves_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('portal_jobs_pkey1'))
    )
    op.create_index(op.f('ix_portal_jobs_title'), 'portal_jobs', ['title'], unique=False)
    op.create_index(op.f('ix_portal_jobs_source'), 'portal_jobs', ['source'], unique=False)
    op.create_index(op.f('ix_portal_jobs_slug'), 'portal_jobs', ['slug'], unique=True)
    op.create_index(op.f('ix_portal_jobs_posted_at'), 'portal_jobs', [sa.literal_column('posted_at DESC')], unique=False)
    op.create_index(op.f('ix_portal_jobs_opportunity_type'), 'portal_jobs', ['opportunity_type'], unique=False)
    op.create_index(op.f('ix_portal_jobs_opportunity_category'), 'portal_jobs', ['opportunity_category'], unique=False)
    op.create_index(op.f('ix_portal_jobs_location'), 'portal_jobs', ['location'], unique=False)
    op.create_index(op.f('ix_portal_jobs_is_active'), 'portal_jobs', ['is_active'], unique=False)
    op.create_index(op.f('ix_portal_jobs_external_id'), 'portal_jobs', ['external_id'], unique=False)
    op.create_index(op.f('ix_portal_jobs_company'), 'portal_jobs', ['company'], unique=False)
    op.create_index(op.f('ix_portal_jobs_category'), 'portal_jobs', ['category'], unique=False)
    op.drop_index(op.f('ix_portfolio_items_user_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_work_experiences_user_id'), table_name='work_experiences')
    op.drop_table('work_experiences')
    # ### end Alembic commands ###
