"""create_project_collaborators_table

Revision ID: 9a7c9c9ec346
Revises: 82e9cbddf40e
Create Date: 2025-12-13 09:12:15.614634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7c9c9ec346'
down_revision = '82e9cbddf40e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('collaborator_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collaborator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_collaborators_collaborator_id'), 'project_collaborators', ['collaborator_id'], unique=False)
    op.create_index(op.f('ix_project_collaborators_id'), 'project_collaborators', ['id'], unique=False)
    op.create_index(op.f('ix_project_collaborators_requester_id'), 'project_collaborators', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_collaborators_requester_id'), table_name='project_collaborators')
    op.drop_index(op.f('ix_project_collaborators_id'), table_name='project_collaborators')
    op.drop_index(op.f('ix_project_collaborators_collaborator_id'), table_name='project_collaborators')
    op.drop_table('project_collaborators')
    # ### end Alembic commands ###
