"""Add feed and portal tables

Revision ID: a350ac68b170
Revises: cdaa5978d98b
Create Date: 2025-12-15 17:00:42.098140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a350ac68b170'
down_revision = 'cdaa5978d98b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('company_logo_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('salary_period', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('education_requirement', sa.String(length=255), nullable=True),
    sa.Column('years_experience_min', sa.Integer(), nullable=True),
    sa.Column('years_experience_max', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('applies_count', sa.Integer(), nullable=True),
    sa.Column('saves_count', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portal_jobs_active_posted', 'portal_jobs', ['is_active', 'posted_at'], unique=False)
    op.create_index(op.f('ix_portal_jobs_category'), 'portal_jobs', ['category'], unique=False)
    op.create_index(op.f('ix_portal_jobs_company'), 'portal_jobs', ['company'], unique=False)
    op.create_index(op.f('ix_portal_jobs_external_id'), 'portal_jobs', ['external_id'], unique=False)
    op.create_index('ix_portal_jobs_filter', 'portal_jobs', ['category', 'location_type', 'experience_level'], unique=False)
    op.create_index(op.f('ix_portal_jobs_id'), 'portal_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_portal_jobs_is_active'), 'portal_jobs', ['is_active'], unique=False)
    op.create_index(op.f('ix_portal_jobs_location'), 'portal_jobs', ['location'], unique=False)
    op.create_index(op.f('ix_portal_jobs_posted_at'), 'portal_jobs', ['posted_at'], unique=False)
    op.create_index('ix_portal_jobs_search', 'portal_jobs', ['title', 'company', 'location'], unique=False)
    op.create_index(op.f('ix_portal_jobs_slug'), 'portal_jobs', ['slug'], unique=True)
    op.create_index(op.f('ix_portal_jobs_source'), 'portal_jobs', ['source'], unique=False)
    op.create_index(op.f('ix_portal_jobs_title'), 'portal_jobs', ['title'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('post_metadata', sa.Text(), nullable=True),
    sa.Column('media_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_parent_id'), 'comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_reaction_post_user')
    )
    op.create_index(op.f('ix_reactions_id'), 'reactions', ['id'], unique=False)
    op.create_index(op.f('ix_reactions_post_id'), 'reactions', ['post_id'], unique=False)
    op.create_index(op.f('ix_reactions_user_id'), 'reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reactions_user_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_post_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_parent_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_portal_jobs_title'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_source'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_slug'), table_name='portal_jobs')
    op.drop_index('ix_portal_jobs_search', table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_posted_at'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_location'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_is_active'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_id'), table_name='portal_jobs')
    op.drop_index('ix_portal_jobs_filter', table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_external_id'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_company'), table_name='portal_jobs')
    op.drop_index(op.f('ix_portal_jobs_category'), table_name='portal_jobs')
    op.drop_index('ix_portal_jobs_active_posted', table_name='portal_jobs')
    op.drop_table('portal_jobs')
    # ### end Alembic commands ###
