"""consolidated_portal_features

Revision ID: a73a461453b4
Revises: cdaa5978d98b
Create Date: 2025-12-18 16:23:59.579795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73a461453b4'
down_revision = 'cdaa5978d98b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endorsements', sa.Column('weight', sa.Float(), nullable=False))
    op.add_column('endorsements', sa.Column('is_verified_colleague', sa.Boolean(), nullable=True))
    op.add_column('endorsements', sa.Column('experience_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'endorsements', 'work_experiences', ['experience_id'], ['id'], ondelete='SET NULL')
    op.add_column('peer_verification_requests', sa.Column('experience_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'peer_verification_requests', 'work_experiences', ['experience_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('stripe_account_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_stripe_onboarded', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_stripe_account_id'), 'users', ['stripe_account_id'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.add_column('verifications', sa.Column('is_gold_standard', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifications', 'is_gold_standard')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_account_id'), table_name='users')
    op.drop_column('users', 'is_stripe_onboarded')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'stripe_account_id')
    op.drop_constraint(None, 'peer_verification_requests', type_='foreignkey')
    op.drop_column('peer_verification_requests', 'experience_id')
    op.drop_constraint(None, 'endorsements', type_='foreignkey')
    op.drop_column('endorsements', 'experience_id')
    op.drop_column('endorsements', 'is_verified_colleague')
    op.drop_column('endorsements', 'weight')
    # ### end Alembic commands ###
