"""Add template_id to resumes

Revision ID: b504c868d5df
Revises: 6e8fdef75e26
Create Date: 2025-11-28 12:54:01.483665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b504c868d5df'
down_revision = '6e8fdef75e26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('template_id', sa.String(length=50), server_default='modern', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'template_id')
    # ### end Alembic commands ###
