"""Add reputation stats and rating dimensions tables

Revision ID: cdaa5978d98b
Revises: 1456ffde2e15
Create Date: 2025-12-15 04:14:03.749400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdaa5978d98b'
down_revision = '1456ffde2e15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
