"""add_resume_upload_fields

Revision ID: d045b3384f88
Revises: 1a5e4dae1c7a
Create Date: 2025-12-03 22:14:08.085369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd045b3384f88'
down_revision = '1a5e4dae1c7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_path', sa.String(length=512), nullable=True))
    op.add_column('resumes', sa.Column('status', sa.String(length=50), server_default='draft', nullable=False))
    op.add_column('resumes', sa.Column('analysis_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resumes', sa.Column('ats_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'ats_score')
    op.drop_column('resumes', 'analysis_results')
    op.drop_column('resumes', 'status')
    op.drop_column('resumes', 'file_path')
    # ### end Alembic commands ###
