"""add_rating_requests_table

Revision ID: d2a46ffae604
Revises: 5fb35329d2ab
Create Date: 2025-12-13 08:39:29.821650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a46ffae604'
down_revision = '5fb35329d2ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('rater_name', sa.String(length=255), nullable=True))
    op.add_column('ratings', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('ratings', sa.Column('work_start_date', sa.DateTime(), nullable=True))
    op.add_column('ratings', sa.Column('work_end_date', sa.DateTime(), nullable=True))
    op.add_column('ratings', sa.Column('relationship_type', sa.String(length=50), nullable=True))
    op.add_column('ratings', sa.Column('is_flagged', sa.Boolean(), nullable=False))
    op.add_column('ratings', sa.Column('flag_reason', sa.Text(), nullable=True))
    op.add_column('ratings', sa.Column('is_reviewed', sa.Boolean(), nullable=False))
    op.add_column('ratings', sa.Column('review_notes', sa.Text(), nullable=True))
    op.drop_constraint(op.f('unique_category_rating'), 'ratings', type_='unique')
    op.create_index(op.f('ix_ratings_is_flagged'), 'ratings', ['is_flagged'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_is_flagged'), table_name='ratings')
    op.create_unique_constraint(op.f('unique_category_rating'), 'ratings', ['rater_id', 'rated_user_id', 'category'], postgresql_nulls_not_distinct=False)
    op.drop_column('ratings', 'review_notes')
    op.drop_column('ratings', 'is_reviewed')
    op.drop_column('ratings', 'flag_reason')
    op.drop_column('ratings', 'is_flagged')
    op.drop_column('ratings', 'relationship_type')
    op.drop_column('ratings', 'work_end_date')
    op.drop_column('ratings', 'work_start_date')
    op.drop_column('ratings', 'company')
    op.drop_column('ratings', 'rater_name')
    # ### end Alembic commands ###
