"""add_user_reputation_stats_table

Revision ID: d31841270db1
Revises: merge_sprint1_2
Create Date: 2026-05-20 09:18:43.454477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd31841270db1'
down_revision = 'merge_sprint1_2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_city'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_feed_ranking'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_is_duplicate'), table_name='opportunities', postgresql_where='(is_duplicate_of IS NULL)')
    op.drop_index(op.f('ix_opportunities_opportunity_category'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_posted_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_quality_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_source_created'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_source_id'), table_name='opportunities')
    op.create_foreign_key(None, 'opportunities', 'opportunities', ['is_duplicate_of'], ['id'])
    op.drop_column('opportunities', 'opportunity_category')
    op.alter_column('verified_reviews', 'is_flagged',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('verified_reviews', 'is_disputed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('verified_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('verified_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verified_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('verified_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('verified_reviews', 'is_disputed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('verified_reviews', 'is_flagged',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('opportunities', sa.Column('opportunity_category', sa.VARCHAR(length=50), server_default=sa.text("'jobs'::character varying"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.create_index(op.f('ix_opportunities_source_id'), 'opportunities', ['source_id'], unique=False)
    op.create_index(op.f('ix_opportunities_source_created'), 'opportunities', ['source', 'created_at'], unique=False)
    op.create_index(op.f('ix_opportunities_quality_score'), 'opportunities', ['quality_score'], unique=False)
    op.create_index(op.f('ix_opportunities_posted_at'), 'opportunities', ['posted_at'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_type'), 'opportunities', ['job_type'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_category'), 'opportunities', ['opportunity_category'], unique=False)
    op.create_index(op.f('ix_opportunities_is_duplicate'), 'opportunities', ['is_duplicate_of'], unique=False, postgresql_where='(is_duplicate_of IS NULL)')
    op.create_index(op.f('ix_opportunities_feed_ranking'), 'opportunities', ['is_active', 'quality_score', 'expires_at'], unique=False)
    op.create_index(op.f('ix_opportunities_city'), 'opportunities', ['city'], unique=False)
    # ### end Alembic commands ###
